### ISSUE TITLE
Verify Mobile Functionality

### ISSUE THREAD

**Issue by cjhr95** [MissouriMRR/compakt#52]
Ensure the compakt application scales well onto mobile platforms.
- Check the scaling of all prompts & text
- Ensure users can sign signature canvas on mobile
- Check if logs still save on mobile

**Comment by Lmyszka4** [comment]
Confirmed:
- Logs still save on mobile
- Users can sign signature canvas on mobile

Issues:
- Signing and viewing a signature requires the phone to be horizontal / landscape, and even then, the signature still gets partially cutoff
- Some text within buttons spills out
